[package]
name = "concurrency2"
version = "0.1.0"
edition = "2024"
authors = ["Wang Jian <wangjian0504@gmail.com>"]
license = "MIT"

[dependencies]
anyhow = "1.0.99"
dashmap = "6.1.0"
oneshot = "0.1.11"
rand = "0.9.2"
